#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thuctapnhomdemo
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QuanlyKhoHang")]
	public partial class MydataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_PhieuXuat(tbl_PhieuXuat instance);
    partial void Updatetbl_PhieuXuat(tbl_PhieuXuat instance);
    partial void Deletetbl_PhieuXuat(tbl_PhieuXuat instance);
    partial void Inserttbl_ChiTietPhieuNhap(tbl_ChiTietPhieuNhap instance);
    partial void Updatetbl_ChiTietPhieuNhap(tbl_ChiTietPhieuNhap instance);
    partial void Deletetbl_ChiTietPhieuNhap(tbl_ChiTietPhieuNhap instance);
    partial void Inserttbl_ChiTietPhieuXuat(tbl_ChiTietPhieuXuat instance);
    partial void Updatetbl_ChiTietPhieuXuat(tbl_ChiTietPhieuXuat instance);
    partial void Deletetbl_ChiTietPhieuXuat(tbl_ChiTietPhieuXuat instance);
    partial void Inserttbl_HangHoa(tbl_HangHoa instance);
    partial void Updatetbl_HangHoa(tbl_HangHoa instance);
    partial void Deletetbl_HangHoa(tbl_HangHoa instance);
    partial void Inserttbl_KhachHang(tbl_KhachHang instance);
    partial void Updatetbl_KhachHang(tbl_KhachHang instance);
    partial void Deletetbl_KhachHang(tbl_KhachHang instance);
    partial void Inserttbl_KhoHang(tbl_KhoHang instance);
    partial void Updatetbl_KhoHang(tbl_KhoHang instance);
    partial void Deletetbl_KhoHang(tbl_KhoHang instance);
    partial void Inserttbl_NhaCungCap(tbl_NhaCungCap instance);
    partial void Updatetbl_NhaCungCap(tbl_NhaCungCap instance);
    partial void Deletetbl_NhaCungCap(tbl_NhaCungCap instance);
    partial void Inserttbl_NhanVienKho(tbl_NhanVienKho instance);
    partial void Updatetbl_NhanVienKho(tbl_NhanVienKho instance);
    partial void Deletetbl_NhanVienKho(tbl_NhanVienKho instance);
    partial void Inserttbl_NhomSanPham(tbl_NhomSanPham instance);
    partial void Updatetbl_NhomSanPham(tbl_NhomSanPham instance);
    partial void Deletetbl_NhomSanPham(tbl_NhomSanPham instance);
    partial void Inserttbl_PhieuNhap(tbl_PhieuNhap instance);
    partial void Updatetbl_PhieuNhap(tbl_PhieuNhap instance);
    partial void Deletetbl_PhieuNhap(tbl_PhieuNhap instance);
    #endregion
		
		public MydataDataContext() : 
				base(global::Thuctapnhomdemo.Properties.Settings.Default.QuanlyKhoHangConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MydataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MydataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MydataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MydataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_PhieuXuat> tbl_PhieuXuats
		{
			get
			{
				return this.GetTable<tbl_PhieuXuat>();
			}
		}
		
		public System.Data.Linq.Table<tbl_ChiTietPhieuNhap> tbl_ChiTietPhieuNhaps
		{
			get
			{
				return this.GetTable<tbl_ChiTietPhieuNhap>();
			}
		}
		
		public System.Data.Linq.Table<tbl_ChiTietPhieuXuat> tbl_ChiTietPhieuXuats
		{
			get
			{
				return this.GetTable<tbl_ChiTietPhieuXuat>();
			}
		}
		
		public System.Data.Linq.Table<tbl_HangHoa> tbl_HangHoas
		{
			get
			{
				return this.GetTable<tbl_HangHoa>();
			}
		}
		
		public System.Data.Linq.Table<tbl_KhachHang> tbl_KhachHangs
		{
			get
			{
				return this.GetTable<tbl_KhachHang>();
			}
		}
		
		public System.Data.Linq.Table<tbl_KhoHang> tbl_KhoHangs
		{
			get
			{
				return this.GetTable<tbl_KhoHang>();
			}
		}
		
		public System.Data.Linq.Table<tbl_NhaCungCap> tbl_NhaCungCaps
		{
			get
			{
				return this.GetTable<tbl_NhaCungCap>();
			}
		}
		
		public System.Data.Linq.Table<tbl_NhanVienKho> tbl_NhanVienKhos
		{
			get
			{
				return this.GetTable<tbl_NhanVienKho>();
			}
		}
		
		public System.Data.Linq.Table<tbl_NhomSanPham> tbl_NhomSanPhams
		{
			get
			{
				return this.GetTable<tbl_NhomSanPham>();
			}
		}
		
		public System.Data.Linq.Table<tbl_PhieuNhap> tbl_PhieuNhaps
		{
			get
			{
				return this.GetTable<tbl_PhieuNhap>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CTPhieuNhap_DELETE")]
		public int CTPhieuNhap_DELETE([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string sophieunhap, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string mahanghoa)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sophieunhap, mahanghoa);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PhieuXuat_Them")]
		public int PhieuXuat_Them([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string sophieuxuat, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> ngaylapphieu, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string nguoilapphieu, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,0)")] System.Nullable<decimal> tongtien, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string makhachang)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sophieuxuat, ngaylapphieu, nguoilapphieu, tongtien, makhachang);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CTPhieuNhap_EDIT")]
		public int CTPhieuNhap_EDIT([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string sophieunhap, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string mahanghoa, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,0)")] System.Nullable<decimal> dongianhap, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> soluong)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sophieunhap, mahanghoa, dongianhap, soluong);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CTPhieuNhap_Them")]
		public int CTPhieuNhap_Them([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string sophieunhap, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string mahanghoa, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,0)")] System.Nullable<decimal> dongianhap, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> soluong)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sophieunhap, mahanghoa, dongianhap, soluong);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CTPhieuXuat_DELETE")]
		public int CTPhieuXuat_DELETE([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string sophieuxuat, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string mahanghoa)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sophieuxuat, mahanghoa);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CTPhieuXuat_EDIT")]
		public int CTPhieuXuat_EDIT([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string sophieuxuat, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string mahanghoa, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,0)")] System.Nullable<decimal> dongiaban, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> soluong)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sophieuxuat, mahanghoa, dongiaban, soluong);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CTPhieuXuat_Them")]
		public int CTPhieuXuat_Them([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string sophieuxuat, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string mahanghoa, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,0)")] System.Nullable<decimal> dongiaban, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> soluong)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sophieuxuat, mahanghoa, dongiaban, soluong);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.HangHoa_DELETE")]
		public int HangHoa_DELETE([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string mahh)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mahh);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.HangHoa_EDIT")]
		public int HangHoa_EDIT([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string mahh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string tennhh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,0)")] System.Nullable<decimal> dongia, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string donvitinh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string manhom)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mahh, tennhh, dongia, donvitinh, manhom);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.HangHoa_Them")]
		public int HangHoa_Them([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string mahh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string tennhh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,0)")] System.Nullable<decimal> dongia, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(10)")] string donvitinh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string manhom)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mahh, tennhh, dongia, donvitinh, manhom);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.KhachHang_DELETE")]
		public int KhachHang_DELETE([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string makh)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), makh);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.KhachHang_EDIT")]
		public int KhachHang_EDIT([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string makh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string tennkh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string diachi, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string sdt)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), makh, tennkh, diachi, sdt);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.KhachHang_Them")]
		public int KhachHang_Them([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string makh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string tennkh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(10)")] string diachi, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string sdt)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), makh, tennkh, diachi, sdt);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.KhoHang_DELETE")]
		public int KhoHang_DELETE([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string makho)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), makho);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.KhoHang_EDIT")]
		public int KhoHang_EDIT([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string makho, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string tenkho)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), makho, tenkho);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.KhoHang_Them")]
		public int KhoHang_Them([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string makho, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string tenkho)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), makho, tenkho);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.NhaCungCap_DELETE")]
		public int NhaCungCap_DELETE([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string mancc)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mancc);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.NhaCungCap_EDIT")]
		public int NhaCungCap_EDIT([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string mancc, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string tenncc, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string diachi, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string sdt)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mancc, tenncc, diachi, sdt);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.NhaCungCap_Them")]
		public int NhaCungCap_Them([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string mancc, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string tenncc, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string diachi, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string sdt)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mancc, tenncc, diachi, sdt);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.NhanVienKho_DELETE")]
		public int NhanVienKho_DELETE([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string manv)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), manv);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.NhanVienKho_EDIT")]
		public int NhanVienKho_EDIT([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string manv, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string tennv, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string tuoi, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string sdt)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), manv, tennv, tuoi, sdt);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.NhanVienKho_Them")]
		public int NhanVienKho_Them([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string manv, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string tennv, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string tuoi, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string sdt)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), manv, tennv, tuoi, sdt);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.NhonSanPham_DELETE")]
		public int NhonSanPham_DELETE([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string manhom)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), manhom);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.NhonSanPham_EDIT")]
		public int NhonSanPham_EDIT([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string manhom, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string tennhom, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string makho)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), manhom, tennhom, makho);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.NhonSanPham_Them")]
		public int NhonSanPham_Them([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string manhom, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string tennhom, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string makho)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), manhom, tennhom, makho);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PhieuNhap_DELETE")]
		public int PhieuNhap_DELETE([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string sophieunhap)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sophieunhap);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PhieuNhap_EDIT")]
		public int PhieuNhap_EDIT([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string sophieunhap, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> ngaylapphieu, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string nguoilapphieu, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,0)")] System.Nullable<decimal> tongtien, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string manhom, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string mancc)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sophieunhap, ngaylapphieu, nguoilapphieu, tongtien, manhom, mancc);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PhieuNhap_Them")]
		public int PhieuNhap_Them([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string sophieunhap, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> ngaylapphieu, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string nguoilapphieu, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,0)")] System.Nullable<decimal> tongtien, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string manhom, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string mancc)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sophieunhap, ngaylapphieu, nguoilapphieu, tongtien, manhom, mancc);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PhieuXuat_DELETE")]
		public int PhieuXuat_DELETE([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string sophieuxuat)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sophieuxuat);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PhieuXuat_EDIT")]
		public int PhieuXuat_EDIT([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string sophieuxuat, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> ngaylapphieu, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string nguoilapphieu, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,0)")] System.Nullable<decimal> tongtien, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string makhachang)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sophieuxuat, ngaylapphieu, nguoilapphieu, tongtien, makhachang);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.KH_select")]
		public ISingleResult<KH_selectResult> KH_select()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<KH_selectResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.HH_select")]
		public ISingleResult<HH_selectResult> HH_select()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<HH_selectResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.NV_select")]
		public ISingleResult<NV_selectResult> NV_select()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<NV_selectResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.NSP_select")]
		public ISingleResult<NSP_selectResult> NSP_select()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<NSP_selectResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_PhieuXuat")]
	public partial class tbl_PhieuXuat : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Sophieuxuat;
		
		private System.Nullable<System.DateTime> _Ngaylapphieu;
		
		private string _Nguoilapphieu;
		
		private System.Nullable<decimal> _Tongtien;
		
		private string _Makhachhang;
		
		private EntitySet<tbl_ChiTietPhieuXuat> _tbl_ChiTietPhieuXuats;
		
		private EntityRef<tbl_KhachHang> _tbl_KhachHang;
		
		private EntityRef<tbl_NhanVienKho> _tbl_NhanVienKho;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSophieuxuatChanging(string value);
    partial void OnSophieuxuatChanged();
    partial void OnNgaylapphieuChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaylapphieuChanged();
    partial void OnNguoilapphieuChanging(string value);
    partial void OnNguoilapphieuChanged();
    partial void OnTongtienChanging(System.Nullable<decimal> value);
    partial void OnTongtienChanged();
    partial void OnMakhachhangChanging(string value);
    partial void OnMakhachhangChanged();
    #endregion
		
		public tbl_PhieuXuat()
		{
			this._tbl_ChiTietPhieuXuats = new EntitySet<tbl_ChiTietPhieuXuat>(new Action<tbl_ChiTietPhieuXuat>(this.attach_tbl_ChiTietPhieuXuats), new Action<tbl_ChiTietPhieuXuat>(this.detach_tbl_ChiTietPhieuXuats));
			this._tbl_KhachHang = default(EntityRef<tbl_KhachHang>);
			this._tbl_NhanVienKho = default(EntityRef<tbl_NhanVienKho>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sophieuxuat", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Sophieuxuat
		{
			get
			{
				return this._Sophieuxuat;
			}
			set
			{
				if ((this._Sophieuxuat != value))
				{
					this.OnSophieuxuatChanging(value);
					this.SendPropertyChanging();
					this._Sophieuxuat = value;
					this.SendPropertyChanged("Sophieuxuat");
					this.OnSophieuxuatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaylapphieu", DbType="DateTime")]
		public System.Nullable<System.DateTime> Ngaylapphieu
		{
			get
			{
				return this._Ngaylapphieu;
			}
			set
			{
				if ((this._Ngaylapphieu != value))
				{
					this.OnNgaylapphieuChanging(value);
					this.SendPropertyChanging();
					this._Ngaylapphieu = value;
					this.SendPropertyChanged("Ngaylapphieu");
					this.OnNgaylapphieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nguoilapphieu", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Nguoilapphieu
		{
			get
			{
				return this._Nguoilapphieu;
			}
			set
			{
				if ((this._Nguoilapphieu != value))
				{
					if (this._tbl_NhanVienKho.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnNguoilapphieuChanging(value);
					this.SendPropertyChanging();
					this._Nguoilapphieu = value;
					this.SendPropertyChanged("Nguoilapphieu");
					this.OnNguoilapphieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tongtien", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Tongtien
		{
			get
			{
				return this._Tongtien;
			}
			set
			{
				if ((this._Tongtien != value))
				{
					this.OnTongtienChanging(value);
					this.SendPropertyChanging();
					this._Tongtien = value;
					this.SendPropertyChanged("Tongtien");
					this.OnTongtienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Makhachhang", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Makhachhang
		{
			get
			{
				return this._Makhachhang;
			}
			set
			{
				if ((this._Makhachhang != value))
				{
					if (this._tbl_KhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMakhachhangChanging(value);
					this.SendPropertyChanging();
					this._Makhachhang = value;
					this.SendPropertyChanged("Makhachhang");
					this.OnMakhachhangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_PhieuXuat_tbl_ChiTietPhieuXuat", Storage="_tbl_ChiTietPhieuXuats", ThisKey="Sophieuxuat", OtherKey="Sophieuxuat")]
		public EntitySet<tbl_ChiTietPhieuXuat> tbl_ChiTietPhieuXuats
		{
			get
			{
				return this._tbl_ChiTietPhieuXuats;
			}
			set
			{
				this._tbl_ChiTietPhieuXuats.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_KhachHang_tbl_PhieuXuat", Storage="_tbl_KhachHang", ThisKey="Makhachhang", OtherKey="Makhachhang", IsForeignKey=true)]
		public tbl_KhachHang tbl_KhachHang
		{
			get
			{
				return this._tbl_KhachHang.Entity;
			}
			set
			{
				tbl_KhachHang previousValue = this._tbl_KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._tbl_KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_KhachHang.Entity = null;
						previousValue.tbl_PhieuXuats.Remove(this);
					}
					this._tbl_KhachHang.Entity = value;
					if ((value != null))
					{
						value.tbl_PhieuXuats.Add(this);
						this._Makhachhang = value.Makhachhang;
					}
					else
					{
						this._Makhachhang = default(string);
					}
					this.SendPropertyChanged("tbl_KhachHang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_NhanVienKho_tbl_PhieuXuat", Storage="_tbl_NhanVienKho", ThisKey="Nguoilapphieu", OtherKey="MaNV", IsForeignKey=true)]
		public tbl_NhanVienKho tbl_NhanVienKho
		{
			get
			{
				return this._tbl_NhanVienKho.Entity;
			}
			set
			{
				tbl_NhanVienKho previousValue = this._tbl_NhanVienKho.Entity;
				if (((previousValue != value) 
							|| (this._tbl_NhanVienKho.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_NhanVienKho.Entity = null;
						previousValue.tbl_PhieuXuats.Remove(this);
					}
					this._tbl_NhanVienKho.Entity = value;
					if ((value != null))
					{
						value.tbl_PhieuXuats.Add(this);
						this._Nguoilapphieu = value.MaNV;
					}
					else
					{
						this._Nguoilapphieu = default(string);
					}
					this.SendPropertyChanged("tbl_NhanVienKho");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_ChiTietPhieuXuats(tbl_ChiTietPhieuXuat entity)
		{
			this.SendPropertyChanging();
			entity.tbl_PhieuXuat = this;
		}
		
		private void detach_tbl_ChiTietPhieuXuats(tbl_ChiTietPhieuXuat entity)
		{
			this.SendPropertyChanging();
			entity.tbl_PhieuXuat = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_ChiTietPhieuNhap")]
	public partial class tbl_ChiTietPhieuNhap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Sophieunhap;
		
		private string _Mahanghoa;
		
		private decimal _Dongianhap;
		
		private int _Soluong;
		
		private EntityRef<tbl_HangHoa> _tbl_HangHoa;
		
		private EntityRef<tbl_PhieuNhap> _tbl_PhieuNhap;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSophieunhapChanging(string value);
    partial void OnSophieunhapChanged();
    partial void OnMahanghoaChanging(string value);
    partial void OnMahanghoaChanged();
    partial void OnDongianhapChanging(decimal value);
    partial void OnDongianhapChanged();
    partial void OnSoluongChanging(int value);
    partial void OnSoluongChanged();
    #endregion
		
		public tbl_ChiTietPhieuNhap()
		{
			this._tbl_HangHoa = default(EntityRef<tbl_HangHoa>);
			this._tbl_PhieuNhap = default(EntityRef<tbl_PhieuNhap>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sophieunhap", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Sophieunhap
		{
			get
			{
				return this._Sophieunhap;
			}
			set
			{
				if ((this._Sophieunhap != value))
				{
					if (this._tbl_PhieuNhap.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSophieunhapChanging(value);
					this.SendPropertyChanging();
					this._Sophieunhap = value;
					this.SendPropertyChanged("Sophieunhap");
					this.OnSophieunhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mahanghoa", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Mahanghoa
		{
			get
			{
				return this._Mahanghoa;
			}
			set
			{
				if ((this._Mahanghoa != value))
				{
					if (this._tbl_HangHoa.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMahanghoaChanging(value);
					this.SendPropertyChanging();
					this._Mahanghoa = value;
					this.SendPropertyChanged("Mahanghoa");
					this.OnMahanghoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dongianhap", DbType="Decimal(18,0) NOT NULL")]
		public decimal Dongianhap
		{
			get
			{
				return this._Dongianhap;
			}
			set
			{
				if ((this._Dongianhap != value))
				{
					this.OnDongianhapChanging(value);
					this.SendPropertyChanging();
					this._Dongianhap = value;
					this.SendPropertyChanged("Dongianhap");
					this.OnDongianhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Soluong", DbType="Int NOT NULL")]
		public int Soluong
		{
			get
			{
				return this._Soluong;
			}
			set
			{
				if ((this._Soluong != value))
				{
					this.OnSoluongChanging(value);
					this.SendPropertyChanging();
					this._Soluong = value;
					this.SendPropertyChanged("Soluong");
					this.OnSoluongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_HangHoa_tbl_ChiTietPhieuNhap", Storage="_tbl_HangHoa", ThisKey="Mahanghoa", OtherKey="Mahanghoa", IsForeignKey=true)]
		public tbl_HangHoa tbl_HangHoa
		{
			get
			{
				return this._tbl_HangHoa.Entity;
			}
			set
			{
				tbl_HangHoa previousValue = this._tbl_HangHoa.Entity;
				if (((previousValue != value) 
							|| (this._tbl_HangHoa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_HangHoa.Entity = null;
						previousValue.tbl_ChiTietPhieuNhaps.Remove(this);
					}
					this._tbl_HangHoa.Entity = value;
					if ((value != null))
					{
						value.tbl_ChiTietPhieuNhaps.Add(this);
						this._Mahanghoa = value.Mahanghoa;
					}
					else
					{
						this._Mahanghoa = default(string);
					}
					this.SendPropertyChanged("tbl_HangHoa");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_PhieuNhap_tbl_ChiTietPhieuNhap", Storage="_tbl_PhieuNhap", ThisKey="Sophieunhap", OtherKey="Sophieunhap", IsForeignKey=true)]
		public tbl_PhieuNhap tbl_PhieuNhap
		{
			get
			{
				return this._tbl_PhieuNhap.Entity;
			}
			set
			{
				tbl_PhieuNhap previousValue = this._tbl_PhieuNhap.Entity;
				if (((previousValue != value) 
							|| (this._tbl_PhieuNhap.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_PhieuNhap.Entity = null;
						previousValue.tbl_ChiTietPhieuNhaps.Remove(this);
					}
					this._tbl_PhieuNhap.Entity = value;
					if ((value != null))
					{
						value.tbl_ChiTietPhieuNhaps.Add(this);
						this._Sophieunhap = value.Sophieunhap;
					}
					else
					{
						this._Sophieunhap = default(string);
					}
					this.SendPropertyChanged("tbl_PhieuNhap");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_ChiTietPhieuXuat")]
	public partial class tbl_ChiTietPhieuXuat : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Sophieuxuat;
		
		private string _Mahanghoa;
		
		private decimal _Dongiaban;
		
		private int _Soluong;
		
		private EntityRef<tbl_PhieuXuat> _tbl_PhieuXuat;
		
		private EntityRef<tbl_HangHoa> _tbl_HangHoa;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSophieuxuatChanging(string value);
    partial void OnSophieuxuatChanged();
    partial void OnMahanghoaChanging(string value);
    partial void OnMahanghoaChanged();
    partial void OnDongiabanChanging(decimal value);
    partial void OnDongiabanChanged();
    partial void OnSoluongChanging(int value);
    partial void OnSoluongChanged();
    #endregion
		
		public tbl_ChiTietPhieuXuat()
		{
			this._tbl_PhieuXuat = default(EntityRef<tbl_PhieuXuat>);
			this._tbl_HangHoa = default(EntityRef<tbl_HangHoa>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sophieuxuat", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Sophieuxuat
		{
			get
			{
				return this._Sophieuxuat;
			}
			set
			{
				if ((this._Sophieuxuat != value))
				{
					if (this._tbl_PhieuXuat.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSophieuxuatChanging(value);
					this.SendPropertyChanging();
					this._Sophieuxuat = value;
					this.SendPropertyChanged("Sophieuxuat");
					this.OnSophieuxuatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mahanghoa", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Mahanghoa
		{
			get
			{
				return this._Mahanghoa;
			}
			set
			{
				if ((this._Mahanghoa != value))
				{
					if (this._tbl_HangHoa.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMahanghoaChanging(value);
					this.SendPropertyChanging();
					this._Mahanghoa = value;
					this.SendPropertyChanged("Mahanghoa");
					this.OnMahanghoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dongiaban", DbType="Decimal(18,0) NOT NULL")]
		public decimal Dongiaban
		{
			get
			{
				return this._Dongiaban;
			}
			set
			{
				if ((this._Dongiaban != value))
				{
					this.OnDongiabanChanging(value);
					this.SendPropertyChanging();
					this._Dongiaban = value;
					this.SendPropertyChanged("Dongiaban");
					this.OnDongiabanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Soluong", DbType="Int NOT NULL")]
		public int Soluong
		{
			get
			{
				return this._Soluong;
			}
			set
			{
				if ((this._Soluong != value))
				{
					this.OnSoluongChanging(value);
					this.SendPropertyChanging();
					this._Soluong = value;
					this.SendPropertyChanged("Soluong");
					this.OnSoluongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_PhieuXuat_tbl_ChiTietPhieuXuat", Storage="_tbl_PhieuXuat", ThisKey="Sophieuxuat", OtherKey="Sophieuxuat", IsForeignKey=true)]
		public tbl_PhieuXuat tbl_PhieuXuat
		{
			get
			{
				return this._tbl_PhieuXuat.Entity;
			}
			set
			{
				tbl_PhieuXuat previousValue = this._tbl_PhieuXuat.Entity;
				if (((previousValue != value) 
							|| (this._tbl_PhieuXuat.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_PhieuXuat.Entity = null;
						previousValue.tbl_ChiTietPhieuXuats.Remove(this);
					}
					this._tbl_PhieuXuat.Entity = value;
					if ((value != null))
					{
						value.tbl_ChiTietPhieuXuats.Add(this);
						this._Sophieuxuat = value.Sophieuxuat;
					}
					else
					{
						this._Sophieuxuat = default(string);
					}
					this.SendPropertyChanged("tbl_PhieuXuat");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_HangHoa_tbl_ChiTietPhieuXuat", Storage="_tbl_HangHoa", ThisKey="Mahanghoa", OtherKey="Mahanghoa", IsForeignKey=true)]
		public tbl_HangHoa tbl_HangHoa
		{
			get
			{
				return this._tbl_HangHoa.Entity;
			}
			set
			{
				tbl_HangHoa previousValue = this._tbl_HangHoa.Entity;
				if (((previousValue != value) 
							|| (this._tbl_HangHoa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_HangHoa.Entity = null;
						previousValue.tbl_ChiTietPhieuXuats.Remove(this);
					}
					this._tbl_HangHoa.Entity = value;
					if ((value != null))
					{
						value.tbl_ChiTietPhieuXuats.Add(this);
						this._Mahanghoa = value.Mahanghoa;
					}
					else
					{
						this._Mahanghoa = default(string);
					}
					this.SendPropertyChanged("tbl_HangHoa");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_HangHoa")]
	public partial class tbl_HangHoa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Mahanghoa;
		
		private string _Tenhanghoa;
		
		private string _Donvitinh;
		
		private decimal _Dongia;
		
		private string _Manhom;
		
		private EntitySet<tbl_ChiTietPhieuNhap> _tbl_ChiTietPhieuNhaps;
		
		private EntitySet<tbl_ChiTietPhieuXuat> _tbl_ChiTietPhieuXuats;
		
		private EntityRef<tbl_NhomSanPham> _tbl_NhomSanPham;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMahanghoaChanging(string value);
    partial void OnMahanghoaChanged();
    partial void OnTenhanghoaChanging(string value);
    partial void OnTenhanghoaChanged();
    partial void OnDonvitinhChanging(string value);
    partial void OnDonvitinhChanged();
    partial void OnDongiaChanging(decimal value);
    partial void OnDongiaChanged();
    partial void OnManhomChanging(string value);
    partial void OnManhomChanged();
    #endregion
		
		public tbl_HangHoa()
		{
			this._tbl_ChiTietPhieuNhaps = new EntitySet<tbl_ChiTietPhieuNhap>(new Action<tbl_ChiTietPhieuNhap>(this.attach_tbl_ChiTietPhieuNhaps), new Action<tbl_ChiTietPhieuNhap>(this.detach_tbl_ChiTietPhieuNhaps));
			this._tbl_ChiTietPhieuXuats = new EntitySet<tbl_ChiTietPhieuXuat>(new Action<tbl_ChiTietPhieuXuat>(this.attach_tbl_ChiTietPhieuXuats), new Action<tbl_ChiTietPhieuXuat>(this.detach_tbl_ChiTietPhieuXuats));
			this._tbl_NhomSanPham = default(EntityRef<tbl_NhomSanPham>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mahanghoa", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Mahanghoa
		{
			get
			{
				return this._Mahanghoa;
			}
			set
			{
				if ((this._Mahanghoa != value))
				{
					this.OnMahanghoaChanging(value);
					this.SendPropertyChanging();
					this._Mahanghoa = value;
					this.SendPropertyChanged("Mahanghoa");
					this.OnMahanghoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tenhanghoa", DbType="NVarChar(50)")]
		public string Tenhanghoa
		{
			get
			{
				return this._Tenhanghoa;
			}
			set
			{
				if ((this._Tenhanghoa != value))
				{
					this.OnTenhanghoaChanging(value);
					this.SendPropertyChanging();
					this._Tenhanghoa = value;
					this.SendPropertyChanged("Tenhanghoa");
					this.OnTenhanghoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Donvitinh", DbType="NVarChar(10)")]
		public string Donvitinh
		{
			get
			{
				return this._Donvitinh;
			}
			set
			{
				if ((this._Donvitinh != value))
				{
					this.OnDonvitinhChanging(value);
					this.SendPropertyChanging();
					this._Donvitinh = value;
					this.SendPropertyChanged("Donvitinh");
					this.OnDonvitinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dongia", DbType="Decimal(18,0) NOT NULL")]
		public decimal Dongia
		{
			get
			{
				return this._Dongia;
			}
			set
			{
				if ((this._Dongia != value))
				{
					this.OnDongiaChanging(value);
					this.SendPropertyChanging();
					this._Dongia = value;
					this.SendPropertyChanged("Dongia");
					this.OnDongiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Manhom", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Manhom
		{
			get
			{
				return this._Manhom;
			}
			set
			{
				if ((this._Manhom != value))
				{
					if (this._tbl_NhomSanPham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnManhomChanging(value);
					this.SendPropertyChanging();
					this._Manhom = value;
					this.SendPropertyChanged("Manhom");
					this.OnManhomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_HangHoa_tbl_ChiTietPhieuNhap", Storage="_tbl_ChiTietPhieuNhaps", ThisKey="Mahanghoa", OtherKey="Mahanghoa")]
		public EntitySet<tbl_ChiTietPhieuNhap> tbl_ChiTietPhieuNhaps
		{
			get
			{
				return this._tbl_ChiTietPhieuNhaps;
			}
			set
			{
				this._tbl_ChiTietPhieuNhaps.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_HangHoa_tbl_ChiTietPhieuXuat", Storage="_tbl_ChiTietPhieuXuats", ThisKey="Mahanghoa", OtherKey="Mahanghoa")]
		public EntitySet<tbl_ChiTietPhieuXuat> tbl_ChiTietPhieuXuats
		{
			get
			{
				return this._tbl_ChiTietPhieuXuats;
			}
			set
			{
				this._tbl_ChiTietPhieuXuats.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_NhomSanPham_tbl_HangHoa", Storage="_tbl_NhomSanPham", ThisKey="Manhom", OtherKey="Manhom", IsForeignKey=true)]
		public tbl_NhomSanPham tbl_NhomSanPham
		{
			get
			{
				return this._tbl_NhomSanPham.Entity;
			}
			set
			{
				tbl_NhomSanPham previousValue = this._tbl_NhomSanPham.Entity;
				if (((previousValue != value) 
							|| (this._tbl_NhomSanPham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_NhomSanPham.Entity = null;
						previousValue.tbl_HangHoas.Remove(this);
					}
					this._tbl_NhomSanPham.Entity = value;
					if ((value != null))
					{
						value.tbl_HangHoas.Add(this);
						this._Manhom = value.Manhom;
					}
					else
					{
						this._Manhom = default(string);
					}
					this.SendPropertyChanged("tbl_NhomSanPham");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_ChiTietPhieuNhaps(tbl_ChiTietPhieuNhap entity)
		{
			this.SendPropertyChanging();
			entity.tbl_HangHoa = this;
		}
		
		private void detach_tbl_ChiTietPhieuNhaps(tbl_ChiTietPhieuNhap entity)
		{
			this.SendPropertyChanging();
			entity.tbl_HangHoa = null;
		}
		
		private void attach_tbl_ChiTietPhieuXuats(tbl_ChiTietPhieuXuat entity)
		{
			this.SendPropertyChanging();
			entity.tbl_HangHoa = this;
		}
		
		private void detach_tbl_ChiTietPhieuXuats(tbl_ChiTietPhieuXuat entity)
		{
			this.SendPropertyChanging();
			entity.tbl_HangHoa = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_KhachHang")]
	public partial class tbl_KhachHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Makhachhang;
		
		private string _Tenkhachhang;
		
		private string _Diachi;
		
		private string _Sodienthoai;
		
		private EntitySet<tbl_PhieuXuat> _tbl_PhieuXuats;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMakhachhangChanging(string value);
    partial void OnMakhachhangChanged();
    partial void OnTenkhachhangChanging(string value);
    partial void OnTenkhachhangChanged();
    partial void OnDiachiChanging(string value);
    partial void OnDiachiChanged();
    partial void OnSodienthoaiChanging(string value);
    partial void OnSodienthoaiChanged();
    #endregion
		
		public tbl_KhachHang()
		{
			this._tbl_PhieuXuats = new EntitySet<tbl_PhieuXuat>(new Action<tbl_PhieuXuat>(this.attach_tbl_PhieuXuats), new Action<tbl_PhieuXuat>(this.detach_tbl_PhieuXuats));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Makhachhang", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Makhachhang
		{
			get
			{
				return this._Makhachhang;
			}
			set
			{
				if ((this._Makhachhang != value))
				{
					this.OnMakhachhangChanging(value);
					this.SendPropertyChanging();
					this._Makhachhang = value;
					this.SendPropertyChanged("Makhachhang");
					this.OnMakhachhangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tenkhachhang", DbType="NVarChar(50)")]
		public string Tenkhachhang
		{
			get
			{
				return this._Tenkhachhang;
			}
			set
			{
				if ((this._Tenkhachhang != value))
				{
					this.OnTenkhachhangChanging(value);
					this.SendPropertyChanging();
					this._Tenkhachhang = value;
					this.SendPropertyChanged("Tenkhachhang");
					this.OnTenkhachhangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Diachi", DbType="NVarChar(100)")]
		public string Diachi
		{
			get
			{
				return this._Diachi;
			}
			set
			{
				if ((this._Diachi != value))
				{
					this.OnDiachiChanging(value);
					this.SendPropertyChanging();
					this._Diachi = value;
					this.SendPropertyChanged("Diachi");
					this.OnDiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sodienthoai", DbType="VarChar(10)")]
		public string Sodienthoai
		{
			get
			{
				return this._Sodienthoai;
			}
			set
			{
				if ((this._Sodienthoai != value))
				{
					this.OnSodienthoaiChanging(value);
					this.SendPropertyChanging();
					this._Sodienthoai = value;
					this.SendPropertyChanged("Sodienthoai");
					this.OnSodienthoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_KhachHang_tbl_PhieuXuat", Storage="_tbl_PhieuXuats", ThisKey="Makhachhang", OtherKey="Makhachhang")]
		public EntitySet<tbl_PhieuXuat> tbl_PhieuXuats
		{
			get
			{
				return this._tbl_PhieuXuats;
			}
			set
			{
				this._tbl_PhieuXuats.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_PhieuXuats(tbl_PhieuXuat entity)
		{
			this.SendPropertyChanging();
			entity.tbl_KhachHang = this;
		}
		
		private void detach_tbl_PhieuXuats(tbl_PhieuXuat entity)
		{
			this.SendPropertyChanging();
			entity.tbl_KhachHang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_KhoHang")]
	public partial class tbl_KhoHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Makho;
		
		private string _Tenkho;
		
		private EntitySet<tbl_NhomSanPham> _tbl_NhomSanPhams;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMakhoChanging(string value);
    partial void OnMakhoChanged();
    partial void OnTenkhoChanging(string value);
    partial void OnTenkhoChanged();
    #endregion
		
		public tbl_KhoHang()
		{
			this._tbl_NhomSanPhams = new EntitySet<tbl_NhomSanPham>(new Action<tbl_NhomSanPham>(this.attach_tbl_NhomSanPhams), new Action<tbl_NhomSanPham>(this.detach_tbl_NhomSanPhams));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Makho", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Makho
		{
			get
			{
				return this._Makho;
			}
			set
			{
				if ((this._Makho != value))
				{
					this.OnMakhoChanging(value);
					this.SendPropertyChanging();
					this._Makho = value;
					this.SendPropertyChanged("Makho");
					this.OnMakhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tenkho", DbType="NVarChar(50)")]
		public string Tenkho
		{
			get
			{
				return this._Tenkho;
			}
			set
			{
				if ((this._Tenkho != value))
				{
					this.OnTenkhoChanging(value);
					this.SendPropertyChanging();
					this._Tenkho = value;
					this.SendPropertyChanged("Tenkho");
					this.OnTenkhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_KhoHang_tbl_NhomSanPham", Storage="_tbl_NhomSanPhams", ThisKey="Makho", OtherKey="Makho")]
		public EntitySet<tbl_NhomSanPham> tbl_NhomSanPhams
		{
			get
			{
				return this._tbl_NhomSanPhams;
			}
			set
			{
				this._tbl_NhomSanPhams.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_NhomSanPhams(tbl_NhomSanPham entity)
		{
			this.SendPropertyChanging();
			entity.tbl_KhoHang = this;
		}
		
		private void detach_tbl_NhomSanPhams(tbl_NhomSanPham entity)
		{
			this.SendPropertyChanging();
			entity.tbl_KhoHang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_NhaCungCap")]
	public partial class tbl_NhaCungCap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNCC;
		
		private string _TenNCC;
		
		private string _Diachi;
		
		private string _Sodienthoai;
		
		private EntitySet<tbl_PhieuNhap> _tbl_PhieuNhaps;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNCCChanging(string value);
    partial void OnMaNCCChanged();
    partial void OnTenNCCChanging(string value);
    partial void OnTenNCCChanged();
    partial void OnDiachiChanging(string value);
    partial void OnDiachiChanged();
    partial void OnSodienthoaiChanging(string value);
    partial void OnSodienthoaiChanged();
    #endregion
		
		public tbl_NhaCungCap()
		{
			this._tbl_PhieuNhaps = new EntitySet<tbl_PhieuNhap>(new Action<tbl_PhieuNhap>(this.attach_tbl_PhieuNhaps), new Action<tbl_PhieuNhap>(this.detach_tbl_PhieuNhaps));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNCC", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNCC
		{
			get
			{
				return this._MaNCC;
			}
			set
			{
				if ((this._MaNCC != value))
				{
					this.OnMaNCCChanging(value);
					this.SendPropertyChanging();
					this._MaNCC = value;
					this.SendPropertyChanged("MaNCC");
					this.OnMaNCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNCC", DbType="NVarChar(50)")]
		public string TenNCC
		{
			get
			{
				return this._TenNCC;
			}
			set
			{
				if ((this._TenNCC != value))
				{
					this.OnTenNCCChanging(value);
					this.SendPropertyChanging();
					this._TenNCC = value;
					this.SendPropertyChanged("TenNCC");
					this.OnTenNCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Diachi", DbType="NVarChar(100)")]
		public string Diachi
		{
			get
			{
				return this._Diachi;
			}
			set
			{
				if ((this._Diachi != value))
				{
					this.OnDiachiChanging(value);
					this.SendPropertyChanging();
					this._Diachi = value;
					this.SendPropertyChanged("Diachi");
					this.OnDiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sodienthoai", DbType="VarChar(10)")]
		public string Sodienthoai
		{
			get
			{
				return this._Sodienthoai;
			}
			set
			{
				if ((this._Sodienthoai != value))
				{
					this.OnSodienthoaiChanging(value);
					this.SendPropertyChanging();
					this._Sodienthoai = value;
					this.SendPropertyChanged("Sodienthoai");
					this.OnSodienthoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_NhaCungCap_tbl_PhieuNhap", Storage="_tbl_PhieuNhaps", ThisKey="MaNCC", OtherKey="MaNCC")]
		public EntitySet<tbl_PhieuNhap> tbl_PhieuNhaps
		{
			get
			{
				return this._tbl_PhieuNhaps;
			}
			set
			{
				this._tbl_PhieuNhaps.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_PhieuNhaps(tbl_PhieuNhap entity)
		{
			this.SendPropertyChanging();
			entity.tbl_NhaCungCap = this;
		}
		
		private void detach_tbl_PhieuNhaps(tbl_PhieuNhap entity)
		{
			this.SendPropertyChanging();
			entity.tbl_NhaCungCap = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_NhanVienKho")]
	public partial class tbl_NhanVienKho : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNV;
		
		private string _TenNV;
		
		private string _Sdt;
		
		private System.Nullable<int> _Tuoi;
		
		private EntitySet<tbl_PhieuXuat> _tbl_PhieuXuats;
		
		private EntitySet<tbl_PhieuNhap> _tbl_PhieuNhaps;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNVChanging(string value);
    partial void OnMaNVChanged();
    partial void OnTenNVChanging(string value);
    partial void OnTenNVChanged();
    partial void OnSdtChanging(string value);
    partial void OnSdtChanged();
    partial void OnTuoiChanging(System.Nullable<int> value);
    partial void OnTuoiChanged();
    #endregion
		
		public tbl_NhanVienKho()
		{
			this._tbl_PhieuXuats = new EntitySet<tbl_PhieuXuat>(new Action<tbl_PhieuXuat>(this.attach_tbl_PhieuXuats), new Action<tbl_PhieuXuat>(this.detach_tbl_PhieuXuats));
			this._tbl_PhieuNhaps = new EntitySet<tbl_PhieuNhap>(new Action<tbl_PhieuNhap>(this.attach_tbl_PhieuNhaps), new Action<tbl_PhieuNhap>(this.detach_tbl_PhieuNhaps));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNV", DbType="NVarChar(50)")]
		public string TenNV
		{
			get
			{
				return this._TenNV;
			}
			set
			{
				if ((this._TenNV != value))
				{
					this.OnTenNVChanging(value);
					this.SendPropertyChanging();
					this._TenNV = value;
					this.SendPropertyChanged("TenNV");
					this.OnTenNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sdt", DbType="VarChar(11)")]
		public string Sdt
		{
			get
			{
				return this._Sdt;
			}
			set
			{
				if ((this._Sdt != value))
				{
					this.OnSdtChanging(value);
					this.SendPropertyChanging();
					this._Sdt = value;
					this.SendPropertyChanged("Sdt");
					this.OnSdtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tuoi", DbType="Int")]
		public System.Nullable<int> Tuoi
		{
			get
			{
				return this._Tuoi;
			}
			set
			{
				if ((this._Tuoi != value))
				{
					this.OnTuoiChanging(value);
					this.SendPropertyChanging();
					this._Tuoi = value;
					this.SendPropertyChanged("Tuoi");
					this.OnTuoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_NhanVienKho_tbl_PhieuXuat", Storage="_tbl_PhieuXuats", ThisKey="MaNV", OtherKey="Nguoilapphieu")]
		public EntitySet<tbl_PhieuXuat> tbl_PhieuXuats
		{
			get
			{
				return this._tbl_PhieuXuats;
			}
			set
			{
				this._tbl_PhieuXuats.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_NhanVienKho_tbl_PhieuNhap", Storage="_tbl_PhieuNhaps", ThisKey="MaNV", OtherKey="Nguoilapphieu")]
		public EntitySet<tbl_PhieuNhap> tbl_PhieuNhaps
		{
			get
			{
				return this._tbl_PhieuNhaps;
			}
			set
			{
				this._tbl_PhieuNhaps.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_PhieuXuats(tbl_PhieuXuat entity)
		{
			this.SendPropertyChanging();
			entity.tbl_NhanVienKho = this;
		}
		
		private void detach_tbl_PhieuXuats(tbl_PhieuXuat entity)
		{
			this.SendPropertyChanging();
			entity.tbl_NhanVienKho = null;
		}
		
		private void attach_tbl_PhieuNhaps(tbl_PhieuNhap entity)
		{
			this.SendPropertyChanging();
			entity.tbl_NhanVienKho = this;
		}
		
		private void detach_tbl_PhieuNhaps(tbl_PhieuNhap entity)
		{
			this.SendPropertyChanging();
			entity.tbl_NhanVienKho = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_NhomSanPham")]
	public partial class tbl_NhomSanPham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Manhom;
		
		private string _Tennhom;
		
		private string _Makho;
		
		private EntitySet<tbl_HangHoa> _tbl_HangHoas;
		
		private EntitySet<tbl_PhieuNhap> _tbl_PhieuNhaps;
		
		private EntityRef<tbl_KhoHang> _tbl_KhoHang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnManhomChanging(string value);
    partial void OnManhomChanged();
    partial void OnTennhomChanging(string value);
    partial void OnTennhomChanged();
    partial void OnMakhoChanging(string value);
    partial void OnMakhoChanged();
    #endregion
		
		public tbl_NhomSanPham()
		{
			this._tbl_HangHoas = new EntitySet<tbl_HangHoa>(new Action<tbl_HangHoa>(this.attach_tbl_HangHoas), new Action<tbl_HangHoa>(this.detach_tbl_HangHoas));
			this._tbl_PhieuNhaps = new EntitySet<tbl_PhieuNhap>(new Action<tbl_PhieuNhap>(this.attach_tbl_PhieuNhaps), new Action<tbl_PhieuNhap>(this.detach_tbl_PhieuNhaps));
			this._tbl_KhoHang = default(EntityRef<tbl_KhoHang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Manhom", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Manhom
		{
			get
			{
				return this._Manhom;
			}
			set
			{
				if ((this._Manhom != value))
				{
					this.OnManhomChanging(value);
					this.SendPropertyChanging();
					this._Manhom = value;
					this.SendPropertyChanged("Manhom");
					this.OnManhomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tennhom", DbType="NVarChar(50)")]
		public string Tennhom
		{
			get
			{
				return this._Tennhom;
			}
			set
			{
				if ((this._Tennhom != value))
				{
					this.OnTennhomChanging(value);
					this.SendPropertyChanging();
					this._Tennhom = value;
					this.SendPropertyChanged("Tennhom");
					this.OnTennhomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Makho", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Makho
		{
			get
			{
				return this._Makho;
			}
			set
			{
				if ((this._Makho != value))
				{
					if (this._tbl_KhoHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMakhoChanging(value);
					this.SendPropertyChanging();
					this._Makho = value;
					this.SendPropertyChanged("Makho");
					this.OnMakhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_NhomSanPham_tbl_HangHoa", Storage="_tbl_HangHoas", ThisKey="Manhom", OtherKey="Manhom")]
		public EntitySet<tbl_HangHoa> tbl_HangHoas
		{
			get
			{
				return this._tbl_HangHoas;
			}
			set
			{
				this._tbl_HangHoas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_NhomSanPham_tbl_PhieuNhap", Storage="_tbl_PhieuNhaps", ThisKey="Manhom", OtherKey="Manhom")]
		public EntitySet<tbl_PhieuNhap> tbl_PhieuNhaps
		{
			get
			{
				return this._tbl_PhieuNhaps;
			}
			set
			{
				this._tbl_PhieuNhaps.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_KhoHang_tbl_NhomSanPham", Storage="_tbl_KhoHang", ThisKey="Makho", OtherKey="Makho", IsForeignKey=true)]
		public tbl_KhoHang tbl_KhoHang
		{
			get
			{
				return this._tbl_KhoHang.Entity;
			}
			set
			{
				tbl_KhoHang previousValue = this._tbl_KhoHang.Entity;
				if (((previousValue != value) 
							|| (this._tbl_KhoHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_KhoHang.Entity = null;
						previousValue.tbl_NhomSanPhams.Remove(this);
					}
					this._tbl_KhoHang.Entity = value;
					if ((value != null))
					{
						value.tbl_NhomSanPhams.Add(this);
						this._Makho = value.Makho;
					}
					else
					{
						this._Makho = default(string);
					}
					this.SendPropertyChanged("tbl_KhoHang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_HangHoas(tbl_HangHoa entity)
		{
			this.SendPropertyChanging();
			entity.tbl_NhomSanPham = this;
		}
		
		private void detach_tbl_HangHoas(tbl_HangHoa entity)
		{
			this.SendPropertyChanging();
			entity.tbl_NhomSanPham = null;
		}
		
		private void attach_tbl_PhieuNhaps(tbl_PhieuNhap entity)
		{
			this.SendPropertyChanging();
			entity.tbl_NhomSanPham = this;
		}
		
		private void detach_tbl_PhieuNhaps(tbl_PhieuNhap entity)
		{
			this.SendPropertyChanging();
			entity.tbl_NhomSanPham = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_PhieuNhap")]
	public partial class tbl_PhieuNhap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Sophieunhap;
		
		private System.Nullable<System.DateTime> _Ngaylapphieu;
		
		private string _Nguoilapphieu;
		
		private System.Nullable<decimal> _Tongtien;
		
		private string _Manhom;
		
		private string _MaNCC;
		
		private EntitySet<tbl_ChiTietPhieuNhap> _tbl_ChiTietPhieuNhaps;
		
		private EntityRef<tbl_NhaCungCap> _tbl_NhaCungCap;
		
		private EntityRef<tbl_NhomSanPham> _tbl_NhomSanPham;
		
		private EntityRef<tbl_NhanVienKho> _tbl_NhanVienKho;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSophieunhapChanging(string value);
    partial void OnSophieunhapChanged();
    partial void OnNgaylapphieuChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaylapphieuChanged();
    partial void OnNguoilapphieuChanging(string value);
    partial void OnNguoilapphieuChanged();
    partial void OnTongtienChanging(System.Nullable<decimal> value);
    partial void OnTongtienChanged();
    partial void OnManhomChanging(string value);
    partial void OnManhomChanged();
    partial void OnMaNCCChanging(string value);
    partial void OnMaNCCChanged();
    #endregion
		
		public tbl_PhieuNhap()
		{
			this._tbl_ChiTietPhieuNhaps = new EntitySet<tbl_ChiTietPhieuNhap>(new Action<tbl_ChiTietPhieuNhap>(this.attach_tbl_ChiTietPhieuNhaps), new Action<tbl_ChiTietPhieuNhap>(this.detach_tbl_ChiTietPhieuNhaps));
			this._tbl_NhaCungCap = default(EntityRef<tbl_NhaCungCap>);
			this._tbl_NhomSanPham = default(EntityRef<tbl_NhomSanPham>);
			this._tbl_NhanVienKho = default(EntityRef<tbl_NhanVienKho>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sophieunhap", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Sophieunhap
		{
			get
			{
				return this._Sophieunhap;
			}
			set
			{
				if ((this._Sophieunhap != value))
				{
					this.OnSophieunhapChanging(value);
					this.SendPropertyChanging();
					this._Sophieunhap = value;
					this.SendPropertyChanged("Sophieunhap");
					this.OnSophieunhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaylapphieu", DbType="DateTime")]
		public System.Nullable<System.DateTime> Ngaylapphieu
		{
			get
			{
				return this._Ngaylapphieu;
			}
			set
			{
				if ((this._Ngaylapphieu != value))
				{
					this.OnNgaylapphieuChanging(value);
					this.SendPropertyChanging();
					this._Ngaylapphieu = value;
					this.SendPropertyChanged("Ngaylapphieu");
					this.OnNgaylapphieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nguoilapphieu", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Nguoilapphieu
		{
			get
			{
				return this._Nguoilapphieu;
			}
			set
			{
				if ((this._Nguoilapphieu != value))
				{
					if (this._tbl_NhanVienKho.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnNguoilapphieuChanging(value);
					this.SendPropertyChanging();
					this._Nguoilapphieu = value;
					this.SendPropertyChanged("Nguoilapphieu");
					this.OnNguoilapphieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tongtien", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Tongtien
		{
			get
			{
				return this._Tongtien;
			}
			set
			{
				if ((this._Tongtien != value))
				{
					this.OnTongtienChanging(value);
					this.SendPropertyChanging();
					this._Tongtien = value;
					this.SendPropertyChanged("Tongtien");
					this.OnTongtienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Manhom", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Manhom
		{
			get
			{
				return this._Manhom;
			}
			set
			{
				if ((this._Manhom != value))
				{
					if (this._tbl_NhomSanPham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnManhomChanging(value);
					this.SendPropertyChanging();
					this._Manhom = value;
					this.SendPropertyChanged("Manhom");
					this.OnManhomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNCC", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string MaNCC
		{
			get
			{
				return this._MaNCC;
			}
			set
			{
				if ((this._MaNCC != value))
				{
					if (this._tbl_NhaCungCap.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNCCChanging(value);
					this.SendPropertyChanging();
					this._MaNCC = value;
					this.SendPropertyChanged("MaNCC");
					this.OnMaNCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_PhieuNhap_tbl_ChiTietPhieuNhap", Storage="_tbl_ChiTietPhieuNhaps", ThisKey="Sophieunhap", OtherKey="Sophieunhap")]
		public EntitySet<tbl_ChiTietPhieuNhap> tbl_ChiTietPhieuNhaps
		{
			get
			{
				return this._tbl_ChiTietPhieuNhaps;
			}
			set
			{
				this._tbl_ChiTietPhieuNhaps.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_NhaCungCap_tbl_PhieuNhap", Storage="_tbl_NhaCungCap", ThisKey="MaNCC", OtherKey="MaNCC", IsForeignKey=true)]
		public tbl_NhaCungCap tbl_NhaCungCap
		{
			get
			{
				return this._tbl_NhaCungCap.Entity;
			}
			set
			{
				tbl_NhaCungCap previousValue = this._tbl_NhaCungCap.Entity;
				if (((previousValue != value) 
							|| (this._tbl_NhaCungCap.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_NhaCungCap.Entity = null;
						previousValue.tbl_PhieuNhaps.Remove(this);
					}
					this._tbl_NhaCungCap.Entity = value;
					if ((value != null))
					{
						value.tbl_PhieuNhaps.Add(this);
						this._MaNCC = value.MaNCC;
					}
					else
					{
						this._MaNCC = default(string);
					}
					this.SendPropertyChanged("tbl_NhaCungCap");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_NhomSanPham_tbl_PhieuNhap", Storage="_tbl_NhomSanPham", ThisKey="Manhom", OtherKey="Manhom", IsForeignKey=true)]
		public tbl_NhomSanPham tbl_NhomSanPham
		{
			get
			{
				return this._tbl_NhomSanPham.Entity;
			}
			set
			{
				tbl_NhomSanPham previousValue = this._tbl_NhomSanPham.Entity;
				if (((previousValue != value) 
							|| (this._tbl_NhomSanPham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_NhomSanPham.Entity = null;
						previousValue.tbl_PhieuNhaps.Remove(this);
					}
					this._tbl_NhomSanPham.Entity = value;
					if ((value != null))
					{
						value.tbl_PhieuNhaps.Add(this);
						this._Manhom = value.Manhom;
					}
					else
					{
						this._Manhom = default(string);
					}
					this.SendPropertyChanged("tbl_NhomSanPham");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_NhanVienKho_tbl_PhieuNhap", Storage="_tbl_NhanVienKho", ThisKey="Nguoilapphieu", OtherKey="MaNV", IsForeignKey=true)]
		public tbl_NhanVienKho tbl_NhanVienKho
		{
			get
			{
				return this._tbl_NhanVienKho.Entity;
			}
			set
			{
				tbl_NhanVienKho previousValue = this._tbl_NhanVienKho.Entity;
				if (((previousValue != value) 
							|| (this._tbl_NhanVienKho.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_NhanVienKho.Entity = null;
						previousValue.tbl_PhieuNhaps.Remove(this);
					}
					this._tbl_NhanVienKho.Entity = value;
					if ((value != null))
					{
						value.tbl_PhieuNhaps.Add(this);
						this._Nguoilapphieu = value.MaNV;
					}
					else
					{
						this._Nguoilapphieu = default(string);
					}
					this.SendPropertyChanged("tbl_NhanVienKho");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_ChiTietPhieuNhaps(tbl_ChiTietPhieuNhap entity)
		{
			this.SendPropertyChanging();
			entity.tbl_PhieuNhap = this;
		}
		
		private void detach_tbl_ChiTietPhieuNhaps(tbl_ChiTietPhieuNhap entity)
		{
			this.SendPropertyChanging();
			entity.tbl_PhieuNhap = null;
		}
	}
	
	public partial class KH_selectResult
	{
		
		private string _Makhachhang;
		
		private string _Tenkhachhang;
		
		private string _Diachi;
		
		private string _Sodienthoai;
		
		public KH_selectResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Makhachhang", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Makhachhang
		{
			get
			{
				return this._Makhachhang;
			}
			set
			{
				if ((this._Makhachhang != value))
				{
					this._Makhachhang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tenkhachhang", DbType="NVarChar(50)")]
		public string Tenkhachhang
		{
			get
			{
				return this._Tenkhachhang;
			}
			set
			{
				if ((this._Tenkhachhang != value))
				{
					this._Tenkhachhang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Diachi", DbType="NVarChar(100)")]
		public string Diachi
		{
			get
			{
				return this._Diachi;
			}
			set
			{
				if ((this._Diachi != value))
				{
					this._Diachi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sodienthoai", DbType="VarChar(10)")]
		public string Sodienthoai
		{
			get
			{
				return this._Sodienthoai;
			}
			set
			{
				if ((this._Sodienthoai != value))
				{
					this._Sodienthoai = value;
				}
			}
		}
	}
	
	public partial class HH_selectResult
	{
		
		private string _Mahanghoa;
		
		private string _Tenhanghoa;
		
		private string _Donvitinh;
		
		private decimal _Dongia;
		
		private string _Manhom;
		
		public HH_selectResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mahanghoa", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Mahanghoa
		{
			get
			{
				return this._Mahanghoa;
			}
			set
			{
				if ((this._Mahanghoa != value))
				{
					this._Mahanghoa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tenhanghoa", DbType="NVarChar(50)")]
		public string Tenhanghoa
		{
			get
			{
				return this._Tenhanghoa;
			}
			set
			{
				if ((this._Tenhanghoa != value))
				{
					this._Tenhanghoa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Donvitinh", DbType="NVarChar(10)")]
		public string Donvitinh
		{
			get
			{
				return this._Donvitinh;
			}
			set
			{
				if ((this._Donvitinh != value))
				{
					this._Donvitinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dongia", DbType="Decimal(18,0) NOT NULL")]
		public decimal Dongia
		{
			get
			{
				return this._Dongia;
			}
			set
			{
				if ((this._Dongia != value))
				{
					this._Dongia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Manhom", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Manhom
		{
			get
			{
				return this._Manhom;
			}
			set
			{
				if ((this._Manhom != value))
				{
					this._Manhom = value;
				}
			}
		}
	}
	
	public partial class NV_selectResult
	{
		
		private string _MaNV;
		
		private string _TenNV;
		
		private string _Sdt;
		
		private System.Nullable<int> _Tuoi;
		
		public NV_selectResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					this._MaNV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNV", DbType="NVarChar(50)")]
		public string TenNV
		{
			get
			{
				return this._TenNV;
			}
			set
			{
				if ((this._TenNV != value))
				{
					this._TenNV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sdt", DbType="VarChar(11)")]
		public string Sdt
		{
			get
			{
				return this._Sdt;
			}
			set
			{
				if ((this._Sdt != value))
				{
					this._Sdt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tuoi", DbType="Int")]
		public System.Nullable<int> Tuoi
		{
			get
			{
				return this._Tuoi;
			}
			set
			{
				if ((this._Tuoi != value))
				{
					this._Tuoi = value;
				}
			}
		}
	}
	
	public partial class NSP_selectResult
	{
		
		private string _Manhom;
		
		private string _Tennhom;
		
		private string _Makho;
		
		public NSP_selectResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Manhom", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Manhom
		{
			get
			{
				return this._Manhom;
			}
			set
			{
				if ((this._Manhom != value))
				{
					this._Manhom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tennhom", DbType="NVarChar(50)")]
		public string Tennhom
		{
			get
			{
				return this._Tennhom;
			}
			set
			{
				if ((this._Tennhom != value))
				{
					this._Tennhom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Makho", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Makho
		{
			get
			{
				return this._Makho;
			}
			set
			{
				if ((this._Makho != value))
				{
					this._Makho = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
